#!/bin/bash
# Usage: ./RunMatBG 'outputfile.txt' 
# outputfile.txt will capture all the matlab screen output, can rename
# to whatever you like.

matlab -nodisplay -nodesktop -r "smallbox('$1')" > $2 &
#some of the available data files for smallbox: 
# 'Box_plate_PT_dep_150220_VBR'
# 'Box_plate_con_150220_VBR'
# 'Box_hspace_PT_dep_150220_VBR'
# 'Box_hspace_con_150220_VBR'
stty echo
